name: Test

on: 
  pull_request:
    types: [opened, edited]

jobs:
  # test is the job name
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7.12'
      
      # Get title from PR comment
      - name: Get proposal title from PR body
        run: echo $'${{ github.event.pull_request.body }}' | sed -n '/##/,/##/p'
      
      # Note: uses action of this repository.
      # Will have to be replaced by action name once it is published
      - name: Run action
        uses: ./

      # Set env according to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
      - name: Read generated comment into env
        run: |
          echo 'GENERATED_COMMENT<<EOF' >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/generated_comment.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      # TODO: This has to be replaced with the creation of a PR comment in the future
      # Use this action to create / update a PR comment: https://github.com/marketplace/actions/create-or-update-comment
      # Use this action to find a previous PR comment which should be updated: https://github.com/peter-evans/find-comment
      # Note: You can use ${{ github.event.pull_request.number }}
      - name: Create Issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          title: "Reading suggestions"
          body: ${{ env.GENERATED_COMMENT }}
          pinned: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

