name: Test

on: 
  issues:
    types: [opened, edited]
  push:

jobs:
  # test is the job name
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7.12'

      - name: Run action
        env:
          REPO_FULLNAME: ${{ github.repository }}
        # Specifies the action of this repo?
        uses: ./

      - name: Read Output
        run: |
          cat ${{ GITHUB_WORKSPACE }}/generated_comment.md
          cat ${{ GITHUB_WORKSPACE }}/generated_comment.md >> $GITHUB_ENV
          echo {{ $GENERATED_COMMENT }}

      - run: |
          echo "You are now finished!"
          #echo "From workflow script: REPO_FULLNAME=$REPO_FULLNAME"
