name: Test

on: 
  issues:
    types: [opened, edited]
  push:

jobs:
  # test is the job name
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7.12'

      - name: Run action
        env:
          REPO_FULLNAME: ${{ github.repository }}
        # Specifies the action of this repo?
        uses: ./

      # Set env according to https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
      - name: Read generated comment into env
        run: |
          echo 'GENERATED_COMMENT<<EOF' >> $GITHUB_ENV
          cat $GITHUB_WORKSPACE/generated_comment.md >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - run: echo $GENERATED_COMMENT

      # TODO: This has to be replaced with the creation of a PR comment in the future
      - name: Create Issue
        uses: imjohnbo/issue-bot@3daae12aa54d38685d7ff8459fc8a2aee8cea98b
        with:
          title: "Reading suggestions"
          body: ${{ GENERATED_COMMENT }}
          pinned: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "You are now finished!"
          #echo "From workflow script: REPO_FULLNAME=$REPO_FULLNAME"
